# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setting up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 400 private_key.pem
    - name: Run Ansible Playbook
      run: |
        sudo apt update
        sudo apt install -y ansible
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ${{ secrets.SERVER_IP }}, requirement_2/deploy-playbook.yml --private-key=private_key.pem --user=ec2-user
